"""add status and error to file

Revision ID: 506b20f9c62e
Revises: 943033b8c571
Create Date: 2026-09-01 11:12:50.954541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506b20f9c62e'
down_revision: Union[str, None] = '943033b8c571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('status', sa.String(), nullable=False))
    op.add_column('files', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('memories', sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('memories', sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('memories', sa.Column('supersedes_memory_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'memories', 'memories', ['supersedes_memory_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_column('memories', 'supersedes_memory_id')
    op.drop_column('memories', 'valid_until')
    op.drop_column('memories', 'valid_from')
    op.drop_column('files', 'error')
    op.drop_column('files', 'status')
    # ### end Alembic commands ###
