"""Add unique constraint to file chunks

Revision ID: 6f586f64f0c3
Revises: 9d8091e9b512
Create Date: 2026-09-02 09:50:53.672039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f586f64f0c3'
down_revision: Union[str, None] = '9d8091e9b512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_file_chunk_index', 'file_chunks', ['file_id', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_file_chunk_index', 'file_chunks', type_='unique')
    # ### end Alembic commands ###
