"""Add aggregate_type to outbox_events

Revision ID: 7bae7aef7734
Revises: d8d6c4a42b04
Create Date: 2026-09-02 11:05:13.728323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bae7aef7734'
down_revision: Union[str, None] = 'd8d6c4a42b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiration', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', 'id')
    )
    op.create_index(op.f('ix_idempotency_keys_user_id'), 'idempotency_keys', ['user_id'], unique=False)
    op.add_column('outbox_events', sa.Column('aggregate_type', sa.String(length=50), nullable=False))
    op.add_column('outbox_events', sa.Column('aggregate_id', sa.UUID(), nullable=False))
    op.add_column('outbox_events', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outbox_events', sa.Column('attempts', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate_type'), 'outbox_events', ['aggregate_type'], unique=False)
    op.create_index('ix_outbox_unpublished', 'outbox_events', ['published_at', 'attempts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_unpublished', table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_column('outbox_events', 'attempts')
    op.drop_column('outbox_events', 'published_at')
    op.drop_column('outbox_events', 'aggregate_id')
    op.drop_column('outbox_events', 'aggregate_type')
    op.drop_index(op.f('ix_idempotency_keys_user_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
