"""Add file_hash to files

Revision ID: 831a865e1aa5
Revises: 6f586f64f0c3
Create Date: 2026-09-02 10:11:48.312581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831a865e1aa5'
down_revision: Union[str, None] = '6f586f64f0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_hash')
    # ### end Alembic commands ###
