"""add task lease and retry

Revision ID: 91d6aea05542
Revises: b8437433e82c
Create Date: 2026-09-01 19:29:13.481874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d6aea05542'
down_revision: Union[str, None] = 'b8437433e82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('worker_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('max_retries', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'max_retries')
    op.drop_column('tasks', 'retry_count')
    op.drop_column('tasks', 'lease_expires_at')
    op.drop_column('tasks', 'worker_id')
    # ### end Alembic commands ###
