"""update approval schema

Revision ID: 9d8091e9b512
Revises: 91d6aea05542
Create Date: 2026-09-01 19:51:17.369569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d8091e9b512'
down_revision: Union[str, None] = '91d6aea05542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('task_id', sa.UUID(), nullable=True))
    op.add_column('approval_requests', sa.Column('step_id', sa.String(), nullable=True))
    op.add_column('approval_requests', sa.Column('tool_name', sa.String(), nullable=False))
    op.add_column('approval_requests', sa.Column('arguments_hash', sa.String(), nullable=False))
    op.add_column('approval_requests', sa.Column('risk_level', sa.String(), nullable=False))
    op.add_column('approval_requests', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'approval_requests', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_column('approval_requests', 'resource_type')
    op.drop_column('approval_requests', 'details')
    op.drop_column('approval_requests', 'resource_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('approval_requests', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('approval_requests', sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'approval_requests', type_='foreignkey')
    op.drop_column('approval_requests', 'expires_at')
    op.drop_column('approval_requests', 'risk_level')
    op.drop_column('approval_requests', 'arguments_hash')
    op.drop_column('approval_requests', 'tool_name')
    op.drop_column('approval_requests', 'step_id')
    op.drop_column('approval_requests', 'task_id')
    # ### end Alembic commands ###
