"""add memory provenance

Revision ID: b8437433e82c
Revises: 45a1eb46d501
Create Date: 2026-09-01 19:03:58.922389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8437433e82c'
down_revision: Union[str, None] = '45a1eb46d501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('source_conversation_id', sa.UUID(), nullable=True))
    op.add_column('memories', sa.Column('scope', sa.String(), nullable=False))
    op.create_foreign_key(None, 'memories', 'conversations', ['source_conversation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_column('memories', 'scope')
    op.drop_column('memories', 'source_conversation_id')
    # ### end Alembic commands ###
