"""Add outbox and idempotency models

Revision ID: d8d6c4a42b04
Revises: 831a865e1aa5
Create Date: 2026-09-02 10:39:56.161391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d6c4a42b04'
down_revision: Union[str, None] = '831a865e1aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
