from enum import Enum
from pydantic import BaseModel

class ErrorCode(str, Enum):
    AUTH_ERROR = "AUTH_ERROR"
    FORBIDDEN = "FORBIDDEN"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    MODEL_TIMEOUT = "MODEL_TIMEOUT"
    MODEL_ERROR = "MODEL_ERROR"
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    TOOL_PERMISSION_DENIED = "TOOL_PERMISSION_DENIED"
    TOOL_TIMEOUT = "TOOL_TIMEOUT"
    TOOL_ERROR = "TOOL_ERROR"
    FILE_ERROR = "FILE_ERROR"
    MEMORY_ERROR = "MEMORY_ERROR"
    CONTEXT_LIMIT = "CONTEXT_LIMIT"
    TASK_ERROR = "TASK_ERROR"
    TASK_CANCELLED = "TASK_CANCELLED"
    SERVER_ERROR = "SERVER_ERROR"

class APIErrorDetail(BaseModel):
    code: ErrorCode
    message: str
    details: dict = {}
